Repository 100-hours-a-week/9_meow_fe, pull requests merged in 2025-05, with the labels that each got.

#36 feat: 게시글 상세보기 UI 구현
  package-lock.json
  package.json
  src/app/detail/[postId]/DetailPostPage.tsx
  src/assets/dummy-post-detail.ts
  src/components/common/PostCard/PostContent.tsx
  src/components/common/PostCard/PostFooter.tsx
  src/components/common/PostCard/PostHeader.tsx
  src/components/pages/PostDetail/ImageCarousel.tsx
  src/components/pages/index.tsx
  src/components/ui/carousel.tsx
  src/types/PostDetailData.ts
Labels: FE, ✨feat

#41 feat: 게시글 API 연결 수정 및 게시글 상세보기 구현
  src/app/MainPage.tsx
  src/app/detail/[postId]/DetailPostPage.tsx
  src/assets/dummy-post-detail.ts
  src/assets/dummy-posts.ts
  src/components/common/PostCard/PostContent.tsx
  src/components/pages/PostForm/PostContentInput.tsx
  src/components/pages/PostForm/SelectEmotion.tsx
  src/components/pages/PostForm/validation/validateFileLength.ts
  src/components/pages/PostForm/validation/validateFileSize.ts
  src/hooks/common/useObserver.ts
  src/hooks/queries/usePostDetailQuery.ts
  src/hooks/queries/usePostListInfiniteQuery.ts
  src/service/post.ts
  src/store/useCreatePostStore.ts
  src/types/PostDetailData.ts
  src/types/PostSummaryData.ts
  src/types/ValidationReturnType.ts
Labels: FE, ✨feat, 🐞bugfix

#46 feat: 게시글 작성 로딩 처리
  src/app/create/CreatePostPage.tsx
  src/components/pages/PostForm/CreatePostForm.tsx
  src/components/pages/PostForm/ImageInput.tsx
  src/components/pages/PostForm/PostContentInput.tsx
  src/components/pages/PostForm/SelectEmotion.tsx
  src/hooks/useImageUpload.ts
  src/store/useCreatePostStore.ts
Labels: FE, ✨feat, ♻️refactor

#50 feat: 회원가입 오류 수정 및 게시글 작성시 Token 함께 전송
  src/api/post.ts
  src/api/queries/loginQueries.ts
  src/api/queries/postQueries.ts
  src/api/queries/signupQueries.ts
  src/api/types.ts
  src/app/login/LoginPage.tsx
  src/app/redirect/RedirectPage.tsx
  src/components/pages/MemberForm/SignupForm.tsx
  src/components/pages/PostForm/ImageInput.tsx
Labels: FE, ✨feat, 🐞bugfix

#52 fix: login 요청 두번 되는 오류 & 닉네임 유효성 검사 확실하게
  src/components/pages/MemberForm/NicknameInput.tsx
  src/components/pages/MemberForm/SignupForm.tsx
  src/components/pages/MemberForm/validation/validateNickname.ts
Labels: FE, 🐞bugfix

#54 fix: infiniteQuery pageParam 오류 수정
  src/api/queries/postQueries.ts
  src/app/MainPage.tsx
Labels: FE, 🐞bugfix

#57 feat: Create FE CI
  .github/workflows/ci.yml
  vite.config.ts
Labels: FE, ✨feat

#59 fix: port 번호 수정
  vite.config.ts
Labels: FE, 🐞bugfix

#61 modify ci condition
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: 🐞bugfix

#63 feat: refresh token 사용
  src/api/login.ts
  src/api/queries/loginQueries.ts
  src/api/queries/postQueries.ts
  src/api/types.ts
  src/components/pages/PostForm/CreatePostForm.tsx
Labels: FE, ✨feat

#72 docs: PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: FE, 📝docs

#76 feat: 로그아웃 기능 구현
  public/loginButton/kakao_login_large_narrow.png
  public/loginButton/kakao_login_medium_narrow.png
  src/app/login/LoginPage.tsx
  src/components/pages/Login/LoginButton.tsx
  src/components/pages/Login/LogoutButton.tsx
  src/components/pages/index.tsx
Labels: FE, ✨feat

#87 fix: token으로 게시글 조회시 성능 최적화
  src/api/instance/authInstance.ts
  src/api/instance/formInstance.ts
  src/api/login.ts
  src/api/queries/loginQueries.ts
  src/api/queries/postQueries.ts
  src/app/MainPage.tsx
  src/components/common/PostCard/PostFooter.tsx
  src/components/pages/PostForm/CreatePostForm.tsx
Labels: FE, 🐞bugfix, ♻️refactor

#90 86/fix/token으로 게시글 조회 성능 최적화
  src/api/instance/authInstance.ts
  src/api/instance/formInstance.ts
  src/api/login.ts
  src/api/queries/loginQueries.ts
  src/api/queries/postQueries.ts
  src/app/MainPage.tsx
  src/components/common/PostCard/PostFooter.tsx
  src/components/pages/PostForm/CreatePostForm.tsx
Labels: FE, 🐞bugfix, ♻️refactor

#99 fix: build 에러 수정
  src/components/pages/PostForm/CreatePostForm.tsx
  src/components/pages/PostForm/SelectEmotion.tsx
Labels: FE, 🐞bugfix

#101 feat: 댓글 기능 구현
  public/icon/send.svg
  src/api/comment.ts
  src/api/queries/commentQueries.ts
  src/api/types.ts
  src/app/MainPage.tsx
  src/app/detail/[postId]/DetailPostPage.tsx
  src/components/common/PostCard/PostContent.tsx
  src/components/common/UserItem.tsx
  src/components/pages/Comment/CommentInput.tsx
  src/components/pages/Comment/CommentItem.tsx
  src/components/pages/index.tsx
Labels: FE, ✨feat

#123 fix: 댓글 기능 오류 수정
  index.html
  src/App.tsx
  src/app/create/CreatePostPage.tsx
  src/app/detail/[postId]/DetailPostPage.tsx
  src/components/common/Background.tsx
  src/components/pages/Comment/CommentInput.tsx
  src/index.css
Labels: FE, 🐞bugfix

#125 style: 댓글 입력창 로딩 애니메이션 추가
  src/components/pages/Comment/CommentInput.tsx
Labels: FE, 🎨style
